### ISSUE TITLE
Fetcher slow for larger areas

### ISSUE THREAD

**Issue by NikosAlexandris** [dimartinot/gee_sar_fetcher#2]
Hi @dimartinot,

thank you for this API. I am a newcomer in GEE, and I was looking to essentially create the same 'fetcher' like utility.

I've tried to get some data over a somewhat larger area than the one demonstrated in the example (```top_left = [-104.77431630331856, 41.729889598264826], 
    bottom_right = [-104.65140675742012, 41.81515375846025]```).
It seems that it takes too long to get data over large(r) areas. For example:```top_left = [-104.77431630331856, 41.729889598264826], 
    bottom_right = [-104.65140675742012, 41.81515375846025]``` appears to require hours.

I am aware it is a lot of data. However, maybe the double for loop [](https://github.com/dimartinot/gee_sar_fetcher/blob/6b9e40ec4ab90124547a8cf3de44141279fbc345/geesarfetcher/__init__.py#L125-L126) deserves some multi-processing?

**Comment by dimartinot** [comment]
Dear @NikosAlexandris ,

Thank you for your interest in this code. **GEE has indeed very poor performance with regards to "_download speed_"** concerning SAR data. (it could be intentional as GEE is at first not intended to be a data download library). I have not looked at other data sources such as Landsat but S1-GRD data can take a lot of time to download other larger areas. I will shortly release a new version of the code allowing the user to change the scale parameter. In that matter, they will be able to download larger areas in a faster manner. However, it will come with the price of spatial reoslution. 

Additionally, I was indeed thinking about **parallelising the code** with the matter of the double for loop indeed but I have encountered **concurency errors with GEE** reporting that two queries were computed at the same moment. I now want to investigate wether it **prevents** the ability to **launch multiple asynchronous queries** at once or not.

I will keep you updated with my results.

Best regards,

**EDIT**

It appears to be working, I have not encountered this error again. I am then trying out parallelisation. Thank you for your insightful comments.

**Comment by NikosAlexandris** [comment]
> Dear @NikosAlexandris ,
> 
> Thank you for your interest in this code. **GEE has indeed very poor performance with regards to "_download speed_"** concerning SAR data. (it could be intentional as GEE is at first not intended to be a data download library). I have not looked at other data sources such as Landsat but S1-GRD data can take a lot of time to download other larger areas. I will shortly release a new version of the code allowing the user to change the scale parameter. In that matter, they will be able to download larger areas in a faster manner. However, it will come with the price of spatial reoslution.

Indeed, and it makes sense: bring code to (massive/big) data and not the opposite. For prototyping, however, it's often convenient to work @ home.

Great for the parallelisation.

**Comment by dimartinot** [comment]
Thank you for you pull request, I will now integrate my parallelisation changes to the main code. I was able to bring computation time down to around half an hour for the study case you proposed, when querying over one year.

**Comment by NikosAlexandris** [comment]
May I suggest to expose the `scale` parameter of the `getRegion()` function to the API's `fetch` (or `fetcher` for the matter) function(s)? This would allow to aggregate (eventually over a specific `crs`, `crs` being the other spatially relevant parameter in `getRegion()`) the data and further reduce downloading time.

I'd do another pull request.  All are just suggestions, no expectation to merge-in.

**Comment by dimartinot** [comment]
I think my last commit implements this feature, if I understood you correctly. I do agree with you that it has the potential to improve download time, to the downside of lower spatial resolution.

Tell me if it matches what you expect.

Many thanks,

**Comment by NikosAlexandris** [comment]
Parallelization seems to work. Great work.
